### ISSUE TITLE
Question: Working with ESXi 6.x?

### ISSUE THREAD

**Issue by Napsty** [achinthagunasekara/check_vmware_api#1]
Just a quick question. I see you installed the Perl SDK 6.0, but did you successfully run the plugin on ESXi hosts running 6.0 version?

It seems it doesn't work. I tried both Perl SDK 6.0 and 6.0 U2 with the same result. Plugin doesn't seem to do anything. Tried to access both a ESXi host and the Vcenter Server.

Have you got it running?

**Comment by achinthagunasekara** [comment]
What platform are you running this script on? This is not meant to run on ESXi.
I'm running this on CentOS Linux release 7.2.1511 and connecting to my ESXi VMware ESXi 6.0.0 build-2494585. Nagios picks up returned output.

My environment as below,

``` shell
[root@netmanager1 ~]# cat /etc/*release*
CentOS Linux release 7.2.1511 (Core) 
Derived from Red Hat Enterprise Linux 7.2 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core) 
CentOS Linux release 7.2.1511 (Core) 
cpe:/o:centos:centos:7
```

You should just be able to execute this script on Linux box.
When you run this script, you should see something like below.

``` shell
[root@netmanager1 ~]# /usr/local/nagios/libexec/check_vmware_api.pl 
Usage: check_vmware_api.pl -D <data_center> | -H <host_name> [ -C <cluster_name> ] [ -N <vm_name> ]
    -u <user> -p <pass> | -f <authfile>
    -l <command> [ -s <subcommand> ] [ -T <timeshift> ] [ -i <interval> ]
    [ -x <black_list> ] [ -o <additional_options> ]
    [ -t <timeout> ] [ -w <warn_range> ] [ -c <crit_range> ]
    [ -V ] [ -h ]

Missing argument: command
[root@netmanager1 ~]# 
```

Do you get any error messages?

**Comment by Napsty** [comment]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

Yes, I am able to see the usage output. I suspect a problem with the Perl SDK in the background, but how can I verify this? Do you have a "test" command I can manually use to verify if the Perl SDK works?

**Comment by Napsty** [comment]
Hi, seems I have hit the following bug:
https://communities.vmware.com/message/2298661 
Will try with older libwww/liblwp.

**Comment by achinthagunasekara** [comment]
no worries. let us know how you go 👍

**Comment by Napsty** [comment]
Fixed and documented it here: http://www.claudiokuenzler.com/blog/650/slow-vmware-perl-sdk-soap-request-error-libwww-version
